name: "JeboJek - The Best Jekyll Template"
description: "This is the Description"
main_keywords: "Keyword"
author: "Me"
copyright: "2013"


# Pagination
paginate: 100
paginate_path: "posts/page:num"


# Dependencies
markdown:        rdiscount
pygments:         true

# Permalinks
permalink:        /:categories/:title/index.html


# Server
base_url: /

# Custom vars
